#!/usr/bin/env bash

IMAGE=beehivelab/gpullama3.java-nvidia-openjdk-opencl:latest
if [[ "$1" == "--console" ]]; then
    exec docker run --gpus all --rm -it -v "$PWD":/data "$IMAGE"
else
    exec docker run --gpus all --rm -it -v "$PWD":/data "$IMAGE" "/gpullama3/GPULlama3.java/llama-tornado" "$@"
fi
